baseURL = "/"
languageCode = "de"
title = "Konfidas"
DefaultContentLanguage = "de"
enableRobotsTXT = true
[languages]
  [languages.de]
    contentDir = "content/de"
    languageName = "Deutsch"
    # weight = 10
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    # weight = 20